#!/bin/sh

if [ -z "$__fxcrd_INIT" ]; then

__fxcrd_PATH="$(fxcrd_path)" || {
  echo "Please install fxcrd before running this script !!"
  exit 1
}

if [ -z "$(command -v "fxcrd_source")" ]; then
  . "$__fxcrd_PATH/expansion/sh_fallback/helper"
  . "$__fxcrd_PATH/expansion/sh_fallback/tokenize"
  . "$__fxcrd_PATH/expansion/sh_fallback/macros"
  . "$__fxcrd_PATH/expansion/sh_fallback/compile"
  
  fxcrd_compile() { 
    while echo "$1" | grep -qE "^--"; do
      shift
    done
    __fxcrd_compile $@ 
  }
else
  . "$__fxcrd_PATH/compile"
fi
. "$__fxcrd_PATH/source"

fxcrd_include

__fxcrd_dev() {
  gfxc() {
    cd "$(fxcrd_path)"
  }
}

export __fxcrd_INIT=true

fi
