#!/bin/sh

__fxcrd_modt() {
  local ipath="$__fxcrd_PATH/$1"
  ls "$ipath" | while IFS="" read -r file; do
    stat -c "%Y" "$ipath/$file"
  done | sort | tail -1
}

fxcrd_include() {
  if [ -z "$(ls -A "$(fxcrd_path)/compiled")" ] ||
     [ "$(__fxcrd_modt include)" -gt "$(__fxcrd_modt compiled)" ]; then
    echo "fxcrd: compiling..."
    fxcrd_compile --print "$(fxcrd_path)/include/"*
  fi
  for file in "$__fxcrd_PATH/compiled/"*; do
    . "$file"
  done
}
